#!/usr/bin/env bash
# this script displays information about subdomains passed to it as arguments
get_subdomain_info() {
    local domain=$1
    local subdomain=$2

    dig +short $subdomain.$domain | awk -v subdomain="$subdomain" '
    {
        if (NR == 1) {
            print "The subdomain " subdomain " is a A record and points to " $1
        }
    }'
}

domain=$1
subdomain=$2

if [[ -z $subdomain ]]; then
    for sub in www lb-01 web-01 web-02; do
        get_subdomain_info $domain $sub
    done
else
    get_subdomain_info $domain $subdomain
fi
