#!/usr/bin/env bash
# This script takes an IP address as an argument and pings the IP address
# five times to test the connection to the traget.
if [ $# -eq 0 ]
then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

ip_address=$1

ping -c 5 "$ip_address"
