#!/usr/bin/env bash
# This script debugs an nginx web server and then kills the process afterwards
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo pkill -o nginx
