#!/usr/bin/env bash
# Display "To infinity and beyond" indefinitely with a sleep 2 in between each iteration
# Print "I am invincible!!!" when receiving SIGTERM signal

function handle_sigterm {
    echo "I am invincible!!!"
    exit 0
}

trap 'handle_sigterm' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
