#!/usr/bin/env bash
# this script creates a story from the /etc/passwd file using the content
# from within the file

file="/etc/passwd"

while IFS=: read -r username password uid gid info home shell
do
    echo "The user $username is part of the $gid gang,"\
    "lives in $home and rides $shell."\
    "$uid's place is protected by the passcode $password,"\
    "more info about the user here: $info"
done < "$file"
