#!/usr/bin/env bash
# this script loops from 1 to 10 and displays "bad luck" for the 4th iteration
# "good luck" for the 8th iteration and "Best School" for all other iterations

n=11
bad=4
good=8
count=1

while [ $count -lt $n ]
do
	if [ $count -eq $bad ]
	then
		echo "bad luck"
	elif [ $count -eq $good ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	count=$((count + 1))
done
