#!/usr/bin/env bash
# this script displays numbers from 1 to 20 and:
# displays 4 and then "bad luck from China" for 4th iteration
# displays 9 and then "bad luck from Japan" for 9th iteration
# displays 17 and then "bad luck from Italy" for 17th iteration

n=21
china=4
japan=9
italy=17
count=1

while [ $count -lt $n ]
do
    case $count in
        $china)
	    echo "$count"
	    echo "bad luck from China"
	    ;;
        $japan)
	    echo "$count"
	    echo "bad luck from Japan"
	    ;;
        $italy)
	    echo "$count"
	    echo "bad luck from Italy"
	    ;;
	*)
	    echo "$count"
	    ;;
    esac
    count=$((count + 1))
done
