#!/usr/bin/env bash
# this script keeps track of time by printing the hour and then each minute
# in that hour. It does not keep the real time.

hour=0
minute=0

while [ $hour -lt 13 ]
do
    echo "Hour: $hour"
    while [ $minute -lt 59 ]
    do
        minute=$((minute + 1))
        #sleep 1m
        echo "$minute"
    done
    minute=0
    hour=$((hour + 1))
    #sleep 1m
done
